---
# tasks file for nginx
- name: Update apt cache and install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  notify: Start Nginx

- name: Apply Index.html template
  template:
    src: index.html.j2
    dest: "{{ html_root }}/{{ file_name }}"
    mode: 0644
  notify: Reload Nginx
